version: '3'
services:
  mysql:
    container_name: 'mysql'
    image: mysql
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
       - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
    user: "1000:50"
    command: '--innodb-use-native-aio=0'

  phpmyadmin:
    container_name: 'phpmyadmin'
    image: phpmyadmin/phpmyadmin
    restart: always
    depends_on:
      - mysql
    links:
      - mysql
    ports:
      - 8081:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root

  wordpress:
    container_name: 'wordpress'
    build: .
    restart: always
    links:
      - mysql
    volumes:
      - ./public:/var/www/html/wp-content
      - node-modules:/var/node_modules
    ports:
      - 80:80
      - 3000:3000
      - 3001:3001
    environment:
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
    command: /bin/bash -c "apache2-foreground & gulp"
volumes:
  node-modules: